
version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
  build:
    commands:
      - chmod +x generate-version-file.sh && ./generate-version-file.sh
