
version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - VERSION=$(npm run version --silent)
      - echo $VERSION
  build:
    commands:
      - docker build -t test .
