name: Check Push
on:
  workflow_dispatch:
    inputs:
      release-type:
        description: "Release type"
        required: true
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Checkout project repository
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          token: ${{ secrets.PAT }}
          
    # Configure Git
      - name: Git configuration
        run: |
          git config --global user.email "arshdeepkumar482@gmail.com"
          git config --global user.name "Arshdeep Kumar"

      - name: Bump release version
        if: startsWith(github.event.inputs.release-type, 'pre') != true
        run: |
          echo "NEW_VERSION=$(npm --no-git-tag-version version $RELEASE_TYPE)" >> $GITHUB_ENV
          echo "RELEASE_TAG=latest" >> $GITHUB_ENV
        env:
          RELEASE_TYPE: ${{ github.event.inputs.release-type }}

      # Commit changes
      - name: Commit and package.json changes
        run: |
          git add "package.json"
          git commit -m "chore: release ${{ env.NEW_VERSION }}"    
          
      # Create a release branch
      - name: Create release branch
        run: git checkout -b release/${{ env.NEW_VERSION }}          

      # Push repository changes
      - name: Push changes to repository
        run: |
          git push origin main release/${{ env.NEW_VERSION }} --force
