name: Pr Merged
on:
  push:
    branches:
      - main

jobs:
  if_merged:
    runs-on: ubuntu-latest
    steps:
        - name: Do something
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        run: |
        echo The PR was merged
