name: Pr Merged
on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    runs-on: ubuntu-latest
    steps:
        # To check the github context
      - name: Dump Github context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
        
      - name: Do something
        if: github.event.pull_request.merged == true && github.base_ref == 'main'
        env:
          BASE_REF: ${{ github.base_ref }}
        run: |
         echo The PR was merged
         echo "$BASE_REF"
