name: Delete stale branches

on:
  # Run once a week on monday 10:00 AM
#   schedule:
#     - cron: "*/10 * * * *"

  # Allow workflow to be manually run from the GitHub UI
  workflow_dispatch:

jobs:
  delete_stale_branches:
    runs-on: ubuntu-latest
    name: Delete stale branches
#     container:
#         image: docker://phpdockerio/github-actions-delete-abandoned-branches:latest
    #    credentials:
     #      username: <YOUR_USERNAME>
      #     password: ${{  secrets.DOCKER_CONTAINER_REGISTRY_TOKEN }}                
    steps:
      - name: Delete stale branches
        uses: arshdeepkumar482/github-actions-delete-abandoned-branches@v1
        id: delete_stuff
        with:
          github_token: ${{ github.token }}
          last_commit_age_days: 10
          ignore_branches: main,develop

          # Disable dry run and actually get stuff deleted
          dry_run: no

      - name: Get output
        run: "echo 'Deleted branches: ${{ steps.delete_stuff.outputs.deleted_branches }}'"
