name: "PR Title Check"
on:
  pull_request_target:
    branches:
      - main
      - release/v*

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: PR Title Check
        uses: thehanimo/pr-title-checker@v1.3.4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pass_on_octokit_error: false
          configuration_path: ".github/pr-title-check-config.json"
