name: Publish Package to Github Package

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build_and_publish:
    name: Build & Publish Package
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # setup Docker build action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Publish
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile-publish
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:buildcache,mode=max
          push: true
          build-args: |
            F_GITHUB_TOKEN=${{ secrets.PAT }}
