name: Test Dir
on:
  workflow_dispatch:

jobs:
  # define job to build and publish docker image
  test:
    name: read dir
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: arshdeepkumar482/test-action@v1.0.0
