name: Test Workflow
on:
  workflow_dispatch:
    
    
    s:
     tag:
      type: string
      required: true
  
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Checkout project repository
      - name: Checkout
        uses: actions/checkout@v3

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          registry-url: https://registry.npmjs.org/
          node-version: "16"
          
      # To check the github context
      - name: Dump Github context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
    
      - name: get existing pre-release with the version name
        id: getReleaseByTag
        uses: cardinalby/git-get-release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ github.event.inputs.tag }}
          prerelease: true
        continue-on-error: true
        
      - name: dump
        env:           
          GITHUB_CONTEXT: ${{ toJSON(steps.getReleaseByTag.outputs) }}
        run: |
          echo "$GITHUB_CONTEXT"
       
        
      - name: Delete a pre-release with the existing tag
        if: steps.getReleaseByTag.outputs.prerelease != 'false'
        run: echo "Test Run"
 
          
